// src/features/trips/components/TripForm.tsx
import React, { useState, useEffect, type ChangeEvent } from 'react';
import FormInput from '../../../components/ui/FormInput';
import { tripFormFields } from '../tripFormFields';
import type { Trip } from '../../../types/Trip';

/**
 * Interface defining the props for the unified TripForm component.
 */
interface TripFormProps {
  /** Callback function executed when form inputs pass validation checks. */
  onSubmit: (formData: Trip) => Promise<void>;
  /** Optional initial trip record payload used to pre-populate fields during edits. */
  initialData?: Trip;
}

/**
 * A reusable, data-driven form component for managing trip additions and updates.
 * Loops through a field configuration registry to render input layouts.
 * Fully refactored to utilize Tailwind CSS layouts.
 *
 * @param props - Component configuration properties and state initializers.
 * @returns A JSX element rendering the structured form and validation boundaries.
 */
export default function TripForm({
  onSubmit,
  initialData,
}: TripFormProps): React.JSX.Element {
  // Establish state container matching fields partially derived from the Trip model
  const [formData, setFormData] = useState<Partial<Trip>>({});
  // Tracks submission attempts to conditionally activate inline input error highlights
  const [submitted, setSubmitted] = useState<boolean>(false);

  // Synchronize state if initialData becomes available (critical for async Edit view fetching)
  useEffect(() => {
    if (initialData) {
      setFormData(initialData);
    }
  }, [initialData]);

  /**
   * Updates specific properties inside state boundaries whenever input text changes.
   *
   * @param e - Standard change event generated by an HTML input element.
   * @returns Void.
   */
  const handleInputChange = (e: ChangeEvent<HTMLInputElement>): void => {
    const { name, value } = e.target;
    setFormData((prevData) => ({
      ...prevData,
      [name]: value,
    }));
  };

  /**
   * Validates input parameters and proxies data packets up to parent submission hooks.
   *
   * @param e - Web-standard synthetic form submission event block.
   * @returns Void.
   */
  const handleFormSubmit = (
    e: React.SyntheticEvent<HTMLFormElement, SubmitEvent>,
  ): void => {
    e.preventDefault();
    setSubmitted(true);

    // Verifying that every mandatory field configured in the registry contains a value
    const isFormValid = tripFormFields.every((field) => {
      const value = formData[field.name];
      return value !== undefined && value !== '';
    });

    if (isFormValid) {
      // Casting safely to a concrete Trip interface now that all properties are verified
      onSubmit(formData as Trip);
    }
  };

  return (
    <form onSubmit={handleFormSubmit} className="flex flex-col gap-5">
      {tripFormFields.map((field) => (
        <FormInput
          key={field.name}
          label={field.label}
          name={field.name}
          type={field.type}
          placeholder={field.placeholder}
          value={formData[field.name] || ''}
          onChange={handleInputChange}
          submitted={submitted}
          errorMessage={field.errorMessage}
          prefix={field.prefix}
        />
      ))}

      <div className="mt-6 pt-4 border-t border-gray-200 dark:border-slate-700 flex justify-end transition-colors duration-300">
        <button
          type="submit"
          className="px-6 py-2.5 bg-blue-600 hover:bg-blue-700 text-white font-medium rounded-lg shadow-sm transition-colors duration-200 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 dark:focus:ring-offset-slate-800"
        >
          Save Vacation Details
        </button>
      </div>
    </form>
  );
}
